### ISSUE TITLE
Try to deploy on google app engine platform

### ISSUE THREAD

**Issue by boot-sandre** [synw/infergui#5]
Hey,

I am having problems deploying the application on the appengine platform.

I'm using the standard env. The build and deploy is fully managed.

node 20

To build it's doing a:
 - npm build
To serve it's doing a:
/bin/sh -c exec node server.js

The errors is:
Error: Cannot find module '/workspace/server.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {

**Comment by boot-sandre** [comment]
Documentation appengine

Application startup
================

By default, the runtime starts your application by running node server.js. If you specify a start script in your package.json file, the runtime runs the specified start script instead. For example:

"scripts": {
  "start": "node app.js"
}

For your app to receive HTTP requests, your start script should start a web server that listens on host 0.0.0.0 and the port specified by the PORT [environment variable](https://cloud.google.com/appengine/docs/standard/nodejs/runtime#environment_variables), which is accessible in Node.js as process.env.PORT.

For the best performance, the start script should be lightweight and exclude build steps, because it runs whenever a new instance of your application is created.

You can override this behavior by specifying a script in the [entrypoint field](https://cloud.google.com/appengine/docs/standard/reference/app-yaml#entrypoint) in app.yaml. Instead of running node server.js or a start script, the runtime starts your application with the command you specify in entrypoint.

**Comment by boot-sandre** [comment]
I using now an entrypoint

entrypoint: npm run server

But i don't find a way to define the port. 

The best will be the application fetch the common process.env.PORT.

**Comment by synw** [comment]
Ok it's fixed in the latest commit: https://github.com/synw/infergui/commit/1d03ea77945dface109d7f5904a7bd67775290c1

You can now get the port via the PORT env variable

**Comment by boot-sandre** [comment]
Thank's a lot: https://infergui-dot-poseidon-ml-407202.ew.r.appspot.com/

My conf (app.yaml):

```yaml
runtime: nodejs20
entrypoint: npm run server
service: infergui
```
